name: Numerology FE CI
on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/numerology-fe:latest , ${{ secrets.DOCKERHUB_USERNAME }}/numerology-fe:${{ steps.commit.outputs.short }}

  trigger-super-repo-workflows:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Call dispatch workflow API
        run: |
          curl --location --request POST '${{ secrets.API_URI }}' \
          --header 'Authorization: Bearer ${{ secrets.PAT }}' \
          --header 'Content-Type: application/json' \
          --data '{"ref":"main","inputs":{"run_id":"${{ steps.commit.outputs.short }}","project":"fe"}}'
